networks:
  net:

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./media:/app/media
      - ./static:/app/static
    depends_on:
      - site
    networks:
      - net
  site:
    build: ./cotask
    container_name: site
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - net
    volumes:
      - ./cotask:/app
      - static:/app/templates/src
      - media:/app/media

  db:
    image: postgres:15
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=notification_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - net
    ports:
      - "5432:5432"


volumes:
  postgres_data:
  static:
  media: