networks:
  net:

services:
  site:
    build: ./cotask
    container_name: site
    command: daphne -b 0.0.0.0 -p 8000 cotask.asgi:application
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - net
    volumes:
      - ./cotask/media/avatars:/app/media/avatars
      - ./cotask:/app
      - static:/app/static
    ports:
      - "8000:8000"  # можно убрать, если используете только nginx

  db:
    image: postgres:15
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=notification_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - net
  
  redis:
    image: redis:7-alpine
    container_name: chat_redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static:/app/static
      - ./cotask/media:/app/media
    depends_on:
      - site
    networks:
      - net

volumes:
  postgres_data:
  static:
  media:
