
networks:
  net:

services:
  site:
    build: ./cotask
    container_name: site
    command: ./start.sh  # Используем Gunicorn
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - net
    volumes:
      - ./cotask:/app
      - static:/app/static  # Том для статических файлов
      - media:/app/media    # Том для медиафайлов

  db:
    image: postgres:15
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=notification_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Монтируем в основной конфиг
      - static:/app/static
      - media:/app/media
    depends_on:
      - site
    networks:
      - net

volumes:
  postgres_data:
  static:
  media: