# Generated by Django 5.2.2 on 2025-06-08 16:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="", verbose_name="avatar"
            ),
            preserve_default=False,
        ),
    ]
