# Generated by Django 5.2.2 on 2025-06-07 20:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0002_profile_created_at_profile_location_profile_website"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.UniqueConstraint(
                fields=("user",), name="unique_user_profile"
            ),
        ),
    ]
