# Generated by Django 5.2.2 on 2025-06-07 21:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0003_profile_unique_user_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(
                blank=True,
                related_name="following_profiles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Подписки",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                related_name="followed_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Подписчики",
            ),
        ),
    ]
