from django.urls import path

import remember_line.views


urlpatterns = [
    path(
        "dashboard/",
        remember_line.views.dashboard_view,
        name="card_dashboard",
    ),
    path(
        "dictionary_list/",
        remember_line.views.dictionary_list_view,
        name="dictionary_list",
    ),
    path(
        "dictionary_create/",
        remember_line.views.dictionary_create_view,
        name="dictionary_create",
    ),
    path(
        "card_create/",
        remember_line.views.card_create_view,
        name="card_create",
    ),
    path(
        "review/",
        remember_line.views.card_review_next_view,
        name="card_review_next",
    ),
    path(
        'review/<int:card_id>/',
        remember_line.views.card_review_detail_view,
        name='card_review_detail',
    ),
    path(
        'cards/<int:card_id>/delete/',
        remember_line.views.card_delete,
        name='card_delete',
    ),
    path(
        'dictionary/<int:dict_id>/delete/',
        remember_line.views.dict_delete,
        name='dict_delete',
    ),
    path(
        'dictionaries/<int:pk>/edit-tags/',
        remember_line.views.dictionary_edit_tags,
        name='dictionary_edit_tags',
    ),
    path(
        'dictionary/<int:pk>/',
        remember_line.views.dictionary_detail,
        name='dictionary_detail',
    ),
    path(
        'dictionary/<int:dictionary_id>/add/',
        remember_line.views.dictionary_add,
        name='dictionary_add',
    ),
    path(
        '<str:username>/dictionaries/',
        remember_line.views.user_dictionaries_view,
        name='user_dictionaries',
    ),
    path(
        'card/<int:pk>/edit/',
        remember_line.views.card_edit_view,
        name='card_edit',
    ),
    path(
        "associations/<int:pk>/delete/",
        remember_line.views.delete_association_view,
        name="delete_association",
    ),
    path(
        "cards/<int:card_id>/association/add/",
        remember_line.views.add_association,
        name="add_association"
    ),
]
