# Generated by Django 5.2.2 on 2025-06-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remember_line", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dictionary",
            name="is_language",
            field=models.BooleanField(default=False, verbose_name="Языковой словарь"),
        ),
        migrations.AddField(
            model_name="dictionary",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="Публичный доступ"),
        ),
    ]
