# Generated by Django 5.2.2 on 2025-06-12 08:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.contrib.auth.models import User


class Migration(migrations.Migration):

    dependencies = [
        ("remember_line", "0002_dictionary_is_language_dictionary_is_public"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dictionary",
            name="owner",
            field=models.ForeignKey(
                default=User.objects.first().pk,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_dictionaries",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dictionary",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_dictionaries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
