# Generated by Django 5.2.2 on 2025-06-12 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("remember_line", "0003_dictionary_owner_alter_dictionary_creator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dictionary",
            name="owner",
        ),
    ]
